version: '3'

#env:

tasks:
  build:
    desc: Build the script
    env:
      NODE_OPTIONS: --openssl-legacy-provider
    cmds:
      - yarn run build
  deploy:
    desc: Upload to prod
    cmds:
      - rsync -av dist/* shared-vm.muehlemann-popp.ch:/home/muehlemann_prod/www/
